---
title: "Egzamin (zerowy termin) - Wizualizacja danych - Zestaw 1"
lang: pl
output:
  pdf_document: default
  word_document: default
---

*Zadanie 1 i 2 po 15 pkt. Zadanie 3 - 20 pkt. *

*Punktacja: 46-50 pkt - bdb(5,0); 41-45 pkt - db+(4,5); 36-40 pkt - db(4,0); 31-35 pkt - dst+(3,5); 26-30 pkt - dst(3,0); 0-25 pkt - ndst (2,0).*  

Wykonując pierwsze zadania na 75% można otrzymać przepisanie pozytywnej oceny z ćwiczeń.

Zad.1. Odwzoruj wykres znajdujący się w pliku graficznym 1.png znajdującym się folderze. Odcienie kolorów mogą się różnić, jednak główne barwy muszą być zachowane.
Zapisz powstały wykres w formacie pdf.

Zad.2. W jednym pliku wykonaj poniższe czynności:

* załaduj dane z pliku mieszkania1.xlsx jako ramkę danych (Data Frame),
* stwórz wykres słupkowy pionowy prezentujący dane zawarte w ramce danych (wszystkie dane)
* umieść swój numer indeksu w lewym górnym rogu wykresu.

Wykres powinien być estetyczny i podpisany. Im więcej - tym lepiej.

Zapisz wykres w formacie pdf za pomocą kodu.

Zad.3. W jednym pliku wykonaj poniższe czynności:

* załaduj dane z pliku transport1.xlsx,
* uporządkuj dane tak, aby dane liczbowe były zgodne z koncepcją "czystych danych" (w kolumnach)
* stwórz dwa wykresy kołowe prezentujące względny udział różnych kategorii hoteli w danym roku (wybierz dowolne dwa lata samodzielnie)
* Wykres powinien być estetyczny i podpisany. Im więcej - tym lepiej.

Zapisz wykres w formacie jpg za pomocą kodu.
